import { defineConfig } from "vite-plus";
import path from "path";

// Tests resolve @open-glass/core to source, not packages/core/dist: dist is gitignored, so a stale
// build otherwise produces accurate-looking failures against code that is no longer in the tree.
// The /wasm subpath stays on dist because it is genuinely generated by wasm-pack.
export default defineConfig({
  resolve: {
    alias: {
      "@open-glass/core/wasm": path.resolve(__dirname, "../core/dist/wasm/open_glass_core.js"),
      "@open-glass/core": path.resolve(__dirname, "../core/src/ts/index.ts"),
    },
  },
});
